/// test Data, generated from combinationation of 1062 xib files
let tagAttributeDicts: [String: [String: [String]]] = [
    "font":
        [	"size":		["18", "16", "14", "13", "12", "8", ],
            "key":		["NSOriginalFont", "NSFont", 	],
            "name":		[".AppleSystemUIFont", "PingFangSC-Semibold", "PingFangSC-Medium", "PingFangSC-Regular", ".PingFangSC-Regular", "HelveticaNeue", 	],
            "metaFont":		["menu", "system", "cellTitle", 	],
        ],
    "visualEffectView":
        [	"id":		["Lmy-JC-nev" ],
            "translatesAutoresizingMaskIntoConstraints":		["NO", 	],
            "opaque":		["NO", 	],
            "contentMode":		["scaleToFill", 	],
        ],
    "point":
        [	"key":		["canvasLocation", 	],
            "y":		["102.09895052473765", "..."],
            "x":		["86.956521739130437", "..."],
        ],
    "variation":
        [	"key":		["heightClass=regular-widthClass=regular", "default", 	],
            "constant":		["38", "44", "32", "40", "16", "21", "50", "10", "36", "0.0", "-60", "45", 	],
        ],
    "paragraphStyle":
        [	"minimumLineHeight":		["20", "17", "4", 	],
            "lineHeightMultiple":		["5", "1.3", 	],
            "baseWritingDirection":		["natural", "leftToRight", 	],
            "tighteningFactorForTruncation":		["0.0", 	],
            "lineBreakMode":		["wordWrapping", 	],
            "maximumLineHeight":		["16", "20", 	],
            "defaultTabInterval":		["36", 	],
            "alignment":		["left", "natural", "center", 	],
            "key":		["NSParagraphStyle", 	],
            "allowsDefaultTighteningForTruncation":		["NO", 	],
            "lineSpacing":		["10", "5", "16", 	],
        ],
    "pongPressGestureRecognizer":
        [	"minimumPressDuration":		["0.5", 	],
            "allowableMovement":		["10", 	],
            "id":		["Oko-0O-iMZ" 	],
        ],
    "real":
        [	"key":		["NSStrokeWidth", "value", "NSKern", 	],
            "value":		["16", "22", "0.5", "0.0", "12.5", "3.2000000000000002", "6.25", "21", "11", "19", "18", "5", "8", "6", "1", "0.29999999999999999", "16.5", "10", "4", "30", "1.5", "8.5", "12", "3", "7", "13", "17", "23", "14", "4.5", "10.199999999999999", "9", "38", "0.51000000000000001", "35", "68", "21.5", "25", "20", "7.5", "15", "2", "-0.29999999999999999", "40", 	],
        ],
    "tapGestureRecognizer":
        [	"userLabel":		["Tap ownerAvatar", "Tap mateAvatar", "Unlock Box Gesture", "Family Fund Gesture", "Tap AnyWhere Gesture", "Donate Gesture", 	],
            "cancelsTouchesInView":		["NO", 	],
            "id":		["jhI-aV-mYL", "..."],
        ],
    "segmentedControl":
        [	"opaque":		["NO", 	],
            "segmentControlStyle":		["plain", 	],
            "contentMode":		["scaleToFill", 	],
            "translatesAutoresizingMaskIntoConstraints":		["NO", 	],
            "id":		["GKz-31-1UO", "amI-cZ-odg", 	],
            "fixedFrame":		["YES", 	],
            "selectedSegmentIndex":		["0", 	],
            "contentHorizontalAlignment":		["left", 	],
            "contentVerticalAlignment":		["top", 	],
        ],
    "outlet":
        [	"id":		["3rG-Np-x7m"],
            "property":		["leadingLyricLabel2"],
            "destination":		["XTB-yw-vx9"],
        ],
    "imageView":
        [	"placeholderIntrinsicHeight":		["350", "800", "17", "150", "60", "40", "84", "266", "325", "24", "50", "21", "26", "23", "116", "500", "80", "63", "108", 	],
            "verticalHuggingPriority":		["249", "252", "251", "248", 	],
            "horizontalCompressionResistancePriority":		["100", "1000", "751", 	],
            "misplaced":		["YES", 	],
            "ambiguous":		["YES", 	],
            "id":		["L7t-8p-1FH"],
            "hidden":		["YES", 	],
            "userInteractionEnabled":		["NO", 	],
            "translatesAutoresizingMaskIntoConstraints":		["NO", 	],
            "placeholderIntrinsicWidth":		["302", "56", "300", "84", "30", "37", "24", "63", "375", "80", "29", "348", "48", "23", "20", "273", "295", "110", "243", "359", 	],
            "userLabel":		["AnimationEmoji", "Holy Time Limit Image View", "BackgroundView", "gender", "Image View", "LeftSwing", "RightSwing", "pic", "Background Image View", "Image Preview", "secrectIcon", "Avatar Score Indicator Img View", "Avatar Image View", "dottedline", "AnimationTrickView", "AnimationTrick", "level", "RightUser", "avatar", "Icon Image View", "AnimationEmojiView", "LeftUser", "giftCover", "backgroundLight", "checkin_header", "Avatar Crown Image View", "bg inset shadow", "rewardImage", "AnimationViewEmoji", "Rank Level Limit Image View", "sendAvatar", "wedding_message_background", "arrow", "collect icon", "Wrong Alert Image View", "boxImageView", "Holy Level Limit Image View", "clockImageView", "Mic Image View", "audio", "Add Image View", "BackgroundImageView", "iconView", 	],
            "clipsSubviews":		["YES", 	],
            "alpha":		["0.80000001192092896", "0.80000000000000004", "0.0", 	],
            "adjustsImageSizeForAccessibilityContentSizeCategory":		["YES", 	],
            "horizontalHuggingPriority":		["251", "252", "248", "249", 	],
            "tag":		["2", "118", "33", "13", "3", "60", "32", "11", "61", "30", "117", "110", "6", "55", "1", "4", "12", "5", "10", "31", "120", "301", "109", "9", "62", 	],
            "fixedFrame":		["YES", 	],
            "image":		["voice_stylus"],
            "verticalCompressionResistancePriority":		["751", "100", 	],
            "highlightedImage":		["order_selected", "choiceFriendsSelected", "report_btn_selected", "chat_msg_secret photo_disable", "btn_choose_round_got", "chat_msg_secret photo_destory", 	],
            "customClass":		["OLImageView", "vip_level1", "WPCircleImageView", "YYAnimatedImageView", "WPAvaterView", "FLAnimatedImageView", 	],
            "contentMode":		["scaleAspectFit", "scaleToFill", "scaleAspectFill", "center", "redraw", "top", 	],
        ],
    "capability":
        [	"minToolsVersion":		["12.0", "9.0", "11.0", "6.0", "5.1", "8.0", 	],
            "name":		["Constraints with non-1.0 multipliers", "Alignment constraints with different attributes", "Image references", "Safe area layout guides", "Aspect ratio constraints", "documents saved in the Xcode 8 format", "System colors in document resources", "Constraints to layout margins", 	],
        ],
    "inset":
        [	"key":		["sectionInset", "titleEdgeInsets", "separatorInset", "scrollIndicatorInsets", "contentEdgeInsets", "imageEdgeInsets", 	],
            "minX":		["0.0", "65", "78", "7", "13", "-4", "-22", "10", "20", "-10", "-24", "3", "47", "2", "9", "24", "-35", "45", "-20", "-8", "16", "55", "4", "-15", "5", "50", "-6", "8", "-25", "-33", "-60", "106", "-17", "111", "40", "-5", "14", "-16", "80", "70", 	],
            "maxY":		["0.0", "5", "20", "13", "12", "8", "10", "21", "28", 	],
            "maxX":		["11", "2.2250738585072014e-308", "-4"],
            "minY":		["0.0", "-15", "55", 	],
        ],
    "autoresizingMask":
        [	"flexibleMaxY":		["YES", 	],
            "widthSizable":		["YES", 	],
            "heightSizable":		["YES", 	],
            "flexibleMaxX":		["YES", 	],
            "flexibleMinX":		["YES", 	],
            "key":		["autoresizingMask", 	],
            "flexibleMinY":		["YES", 	],
        ],
    "textInputTraits":
        [	"keyboardType":		["phonePad", "numberPad", "numbersAndPunctuation", "emailAddress", 	],
            "secureTextEntry":		["YES", 	],
            "returnKeyType":		["search", "next", "send", "done", "go", 	],
            "textContentType":		["password", 	],
            "autocorrectionType":		["no", 	],
            "enablesReturnKeyAutomatically":		["YES", 	],
            "key":		["textInputTraits", 	],
            "autocapitalizationType":		["sentences", 	],
        ],
    "viewLayoutGuide":
        [	"id":		["ppV-gM-Jc6"],
            "key":		["safeArea", 	],
        ],
    "blurEffect":
        [	"style":		["dark", "extraLight", 	],
        ],
    "designables":
        [:	],
    "collectionViewFlowLayout":
        [	"key":		["collectionViewLayout", 	],
            "id":		["JBy-Og-k2U"],
            "scrollDirection":		["horizontal", 	],
            "minimumLineSpacing":		["12", "0.0"],
            "customClass":		["..."],
            "minimumInteritemSpacing":		["0.0", "9"],
        ],
    "textTab":
        [	"location":		["168", "56", "84", "336", "140", "308", "252", "112", "28", "196", "224", "280", 	],
            "alignment":		["left", 	],
        ],
    "tableView":
        [	"estimatedSectionHeaderHeight":		["-1", 	],
            "contentInsetAdjustmentBehavior":		["never", 	],
            "sectionFooterHeight":		["-1", "18", "12", "1", "22", "28", 	],
            "allowsSelection":		["NO", 	],
            "insetsLayoutMarginsFromSafeArea":		["NO", 	],
            "id":		["w0U-Sw-B2J"],
            "userInteractionEnabled":		["NO", 	],
            "showsHorizontalScrollIndicator":		["NO", 	],
            "separatorStyle":		["default", "none", 	],
            "estimatedSectionFooterHeight":		["-1", 	],
            "placeholderIntrinsicWidth":		["414", 	],
            "opaque":		["NO", 	],
            "contentViewInsetsToSafeArea":		["NO", 	],
            "rowHeight":		["90", "38", "-1", "48", "62", "60", "44", "52", "24", "70", "64", "72", "45", "36", "50", 	],
            "placeholderIntrinsicHeight":		["515"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "style":		["grouped", "plain"],
            "contentMode":		["scaleToFill"],
            "sectionHeaderHeight":		["12", "18", "1", "28", "-1", "10", "22", 	],
            "alwaysBounceVertical":		["YES"],
            "estimatedRowHeight":		["44", "80", "180", "60", "-1", 	],
            "clipsSubviews":		["YES"],
            "showsVerticalScrollIndicator":		["NO"],
            "fixedFrame":		["YES"],
            "customClass":		["...", "...", "..."],
            "sectionIndexMinimumDisplayRowCount":		["1"],
            "userLabel":		["Mine Song Table View", "Recommend Table View"],
            "keyboardDismissMode":		["onDrag"],
            "scrollEnabled":		["NO"],
            "bouncesZoom":		["NO"],
            "ambiguous":		["YES"],
            "delaysContentTouches":		["NO"],
            "clearsContextBeforeDrawing":		["NO"],
        ],
    "scrollView":
        [	"alwaysBounceHorizontal":		["YES"],
            "scrollEnabled":		["NO"],
            "multipleTouchEnabled":		["YES"],
            "placeholderIntrinsicWidth":		["300"],
            "ambiguous":		["YES"],
            "keyboardDismissMode":		["onDrag"],
            "delaysContentTouches":		["NO"],
            "id":		["yHg-BB-6ZM"],
            "alwaysBounceVertical":		["YES"],
            "userInteractionEnabled":		["NO"],
            "showsVerticalScrollIndicator":		["NO"],
            "placeholderIntrinsicHeight":		["276"],
            "pagingEnabled":		["YES"],
            "showsHorizontalScrollIndicator":		["NO"],
            "directionalLockEnabled":		["YES"],
            "bouncesZoom":		["NO"],
            "insetsLayoutMarginsFromSafeArea":		["NO"],
            "clipsSubviews":		["YES"],
            "bounces":		["NO"],
            "contentMode":		["scaleToFill"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
        ],
    "datePicker":
        [	"datePickerMode":		["date"],
            "id":		["JSh-HE-hQS"],
            "contentMode":		["scaleToFill"],
            "contentVerticalAlignment":		["center"],
            "contentHorizontalAlignment":		["center"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "style":		["wheels"],
        ],
    "accessibilityTraits":
        [	"notEnabled":		["YES"],
            "key":		["traits"],
        ],
    "gestureRecognizers":
        [:	],
    "attributedString":
        [	"key":		["attributedTitle", "attributedText"],
        ],
    "document":
        [	"useTraitCollections":		["YES", 	],
            "colorMatched":		["YES", 	],
            "variant":		["6xAndEarlier", 	],
            "toolsVersion":		["17701", "19158", "19529", "14113", "10117", "21225", "13529", "6254", "9059", "4514", "13771", "13142", "16097", "11762", "21701", "9531", "14109", "16097.2", "17506", "16096", "15400", "15705", "14490.70", "14460.31", "19455", "18122", "21507", "19162", "20037", "15702", "15505", "7702", "17156", "14313.18", "12120", "16097.3", 	],
            "useAutolayout":		["YES", 	],
            "propertyAccessControl":		["none", 	],
            "version":		["3.0", 	],
            "useSafeAreas":		["YES", 	],
            "systemVersion":		["13B42", "15G1212", "15B42", "14F27", "14E17e", "15E65", "14D72i", "16F73", "14E11f", 	],
            "targetRuntime":		["iOS.CocoaTouch", 	],
            "type":		["com.apple.InterfaceBuilder3.CocoaTouch.XIB", 	],
        ],
    "subviews":
        [:	],
    "label":
        [	"textAlignment":		["right", "natural", "center", 	],
            "placeholderIntrinsicHeight":		["12"],
            "numberOfLines":		["0"],
            "userInteractionEnabled":		["NO"],
            "id":		["MAX-7L-gpa"],
            "opaque":		["NO"],
            "text":		["..."],
            "customClass":		[ "婚礼特殊人员设置"],
            "usesAttributedText":		["YES"],
            "adjustsLetterSpacingToFitWidth":		["YES"],
            "adjustsFontSizeToFit":		["NO"],
            "misplaced":		["YES"],
            "baselineAdjustment":		["alignBaselines"],
            "minimumFontSize":		["0.5"],
            "alpha":		[ "0.5"],
            "adjustsFontForContentSizeCategory":		["YES"],
            "verticalCompressionResistancePriority":		["752"],
            "fixedFrame":		["YES"],
            "ambiguous":		["YES"],
            "minimumScaleFactor":		["0.5"],
            "contentMode":		["left", "center", "redraw", "TopLeft"],
            "verticalHuggingPriority":		["251"],
            "placeholderIntrinsicWidth":		["48"],
            "horizontalCompressionResistancePriority":		["740"],
            "hidden":		["YES"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "clipsSubviews":		["YES"],
            "lineBreakMode":		["clip", "characterWrap", "middleTruncation", "wordWrap", "tailTruncation", "headTruncation"],
            "userLabel":		["ipAddressLabel"],
            "tag":		["52"],
            "horizontalHuggingPriority":		["100"],
        ],
    "plugIn":
        [	"version":		["14460.20"],
            "identifier":		["com.apple.InterfaceBuilder.IBCocoaTouchPlugin", 	],
        ],
    "dataDetectorType":
        [	"link":		["YES"],
            "key":		["dataDetectorTypes"],
        ],
    "simulatedOrientationMetrics":
        [	"key":		["orientation"],
        ],
    "fragment":
        [	"content":		[ "该账号已开启", ],
        ],
    "segment":
        [	"title":		["即构", "服务器指定", "腾讯云", "高音质", "普通音质", 	],
        ],
    "designable":
        [	"name":		["Ikb-sz-LTM"],
        ],
    "deployment":
        [	"identifier":		["iOS"],
            "version":		["2304"],
            "defaultVersion":		["1280"],
        ],
    "edgeInsets":
        [	"key":		["layoutMargins"],
            "left":		["0.0", "10"],
            "bottom":		["0.0", "8", 	],
            "top":		["0.0", "8"],
            "right":		["10", "0.0"],
        ],
    "tabStops":
        [:	],
    "userDefinedRuntimeAttributes":
        [:	],
    "resources":
        [:	],
    "tableViewCell":
        [	"id":		["7GQ-Nd-XOB"],
            "indentationWidth":		["10"],
            "customClass":		["WPDiceMessageCell"],
            "preservesSuperviewLayoutMargins":		["YES"],
            "clipsSubviews":		["YES"],
            "selectionStyle":		["none", "default", "gray"],
            "contentMode":		["scaleToFill"],
            "insetsLayoutMarginsFromSafeArea":		["NO"],
            "rowHeight":		["174"],
            "reuseIdentifier":		["WPBubbleCardCell", "WPUserInfoCell", "WPSlotsTableViewCell", "WPVoiceRoomInviteCell", "WPHeatDetailTableViewCell", 	],
            "userLabel":		["Unknown Message Cell - In"],
        ],
    "collectionViewCell":
        [	"opaque":		["NO"],
            "customClass":		["WPGuardLightGiftCell"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "multipleTouchEnabled":		["YES"],
            "contentMode":		["center"],
            "insetsLayoutMarginsFromSafeArea":		["NO"],
            "clipsSubviews":		["YES"],
            "id":		["gTV-IL-0wX"],
            "userLabel":		["Rank List Play Show Cell"],
        ],
    "attributes":
        [:	],
    "button":
        [	"hidden":		["YES"],
            "selected":		["YES"],
            "buttonType":		["system", "roundedRect"],
            "contentMode":		["scaleToFill", "scaleAspectFit"],
            "horizontalHuggingPriority":		["248"],
            "clipsSubviews":		["YES"],
            "placeholderIntrinsicHeight":		["20"],
            "id":		["QUj-AZ-AVs"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "adjustsImageWhenHighlighted":		["NO"],
            "lineBreakMode":		["middleTruncation", "wordWrap", "tailTruncation"],
            "enabled":		["NO"],
            "hasAttributedTitle":		["YES"],
            "userLabel":		["ReadyButton"],
            "opaque":		["NO"],
            "alpha":		["0.29999999999999999"],
            "customClass":		["WPAutoCountDownButton"],
            "fixedFrame":		["YES"],
            "misplaced":		["YES"],
            "placeholderIntrinsicWidth":		["67"],
            "insetsLayoutMarginsFromSafeArea":		["NO"],
            "contentHorizontalAlignment":		["left", "trailing", "center", "right"],
            "ambiguous":		["YES"],
            "semanticContentAttribute":		["forceRightToLeft"],
            "tag":		["42"],
            "contentVerticalAlignment":		["center"],
            "horizontalCompressionResistancePriority":		["250"],
            "userInteractionEnabled":		["NO"],
            "verticalHuggingPriority":		["249"],
            "verticalCompressionResistancePriority":		["751"],
        ],
    "textView":
        [	"translatesAutoresizingMaskIntoConstraints":		["NO"],
            "multipleTouchEnabled":		["YES"],
            "scrollEnabled":		["NO"],
            "userInteractionEnabled":		["NO"],
            "text":		["赶紧给老娘同意！赶紧给老娘同意！赶紧给老娘同意！赶紧给老娘同意！赶紧给老娘同意！赶紧给老娘同意！"],
            "textAlignment":		["center", "natural", 	],
            "selectable":		["NO"],
            "tag":		["4"],
            "showsVerticalScrollIndicator":		["NO"],
            "showsHorizontalScrollIndicator":		["NO"],
            "customClass":		["WPLimitedTextView" 	],
            "usesAttributedText":		["YES", 	],
            "bounces":		["NO", 	],
            "keyboardDismissMode":		["onDrag", 	],
            "clipsSubviews":		["YES", 	],
            "id":		["5qw-V8-08n"],
            "contentMode":		["scaleToFill", 	],
            "editable":		["NO", 	],
        ],
    "simulatedNavigationBarMetrics":
        [	"translucent":		["NO", 	],
            "key":		["simulatedTopBarMetrics", 	],
            "prompted":		["NO", 	],
        ],
    "string":
        [	"base64-UTF8":		["YES", 	],
            "key":		["text", "content", 	],
        ],
    "slider":
        [	"maxValue":		["70", "100", "1", 	],
            "customClass":		["WPDrawSlider", 	],
            "translatesAutoresizingMaskIntoConstraints":		["NO", 	],
            "value":		["100", "0.5", "35", 	],
            "contentMode":		["scaleToFill", 	],
            "contentHorizontalAlignment":		["center", 	],
            "contentVerticalAlignment":		["center", 	],
            "userInteractionEnabled":		["NO", 	],
            "minValue":		["0.0099999997764825821", "0.0", "0.01", 	],
            "id":		["8cG-KM-Usf", "DEC-3e-amU", "eOn-3S-mG2", "6hj-zT-IYW", "32Q-82-d4m", "NW4-6q-Mzu", 	],
            "opaque":		["NO", 	],
        ],
    "device":
        [	"orientation":		["landscape", "portrait", 	],
            "appearance":		["dark", "light", 	],
            "layout":		["fullscreen", 	],
            "id":		["retina4_0", "retina5_5", "retina6_0", "retina6_12", "ipad10_2", "retina6_5", "ipad9_7", "retina6_1", "retina4_7", 	],
        ],
    "connections":
        [:	],
    "buttonConfiguration":
        [	"title":		["修改", " ", "还原设置", 	],
            "key":		["configuration", 	],
            "style":		["plain", 	],
        ],
    "objects":
        [:	],
    "collectionReusableView":
        [	"opaque":		["NO", 	],
            "clipsSubviews":		["YES", 	],
            "customClass":		["WPVipRightCollectionReusableView", 	],
            "multipleTouchEnabled":		["YES", 	],
            "id":		["U6b-Vx-4bR", 	],
            "contentMode":		["center", 	],
        ],
    "outletCollection":
        [	"destination":		["Ap1-Tt-nas"],
            "id":		["rw7-wW-Rhc"],
            "property":		["optionalLimitLabels"],
            "appends":		["YES"],
        ],
    "tableViewCellContentView":
        [	"ambiguous":		["YES"],
            "opaque":		["NO"],
            "tag":		["1"],
            "id":		["RUd-tU-WO8"],
            "multipleTouchEnabled":		["YES"],
            "clipsSubviews":		["YES"],
            "contentMode":		["center"],
            "key":		["contentView"],
            "insetsLayoutMarginsFromSafeArea":		["NO"],
            "tableViewCell":		["bsL-Im-XnV"],
            "preservesSuperviewLayoutMargins":		["YES"],
        ],
    "array":
        [	"key":		["BananaPie-Heavy.otf"],
        ],
    "simulatedMetricsContainer":
        [	"key":		["defaultSimulatedMetrics"],
        ],
    "accessibility":
        [	"key":		["accessibilityConfiguration"],
        ],
    "exclude":
        [	"reference":		["JxR-e1-GeJ"],
        ],
    "action":
        [	"selector":		["onAddBestParnter:"],
            "destination":		["2IN-z6-uhK"],
            "id":		["UQh-zf-2pb"],
            "eventType":		["touchUpOutside", "touchDown", "editingDidEnd", "editingChanged", "valueChanged", "touchUpInside", 	],
        ],
    "collectionView":
        [	"multipleTouchEnabled":		["YES"],
            "directionalLockEnabled":		["YES"],
            "placeholderIntrinsicWidth":		["375"],
            "id":		["BWJ-wh-IIh"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "bouncesZoom":		["NO"],
            "placeholderIntrinsicHeight":		["128"],
            "dataMode":		["none"],
            "customClass":		["WPPoseComposePhotoCollectionView"],
            "contentMode":		["scaleToFill"],
            "showsHorizontalScrollIndicator":		["NO"],
            "pagingEnabled":		["YES"],
            "showsVerticalScrollIndicator":		["NO"],
            "bounces":		["NO"],
            "scrollEnabled":		["NO"],
            "clipsSubviews":		["YES"],
        ],
    "userDefinedRuntimeAttribute":
        [	"type":		["boolean", "number", "string", "image", "color", 	],
            "keyPath":		["endColor", "defaultBgImage", "placeholder", "toolBarSelectColor", "rightInset", "offImage", "onImage", "layer.maskToBounds", "isDirectionVertical", "layer.cornerRadius", "outlineColor", "bottomInset", "outlineWidth", "textVerticalAlignment", "numberOfLines", "adjustsImageWhenHighlighted", "wp_insetsRight", "totalPage", "placeholderColor", "ignoreOriginalColor", "isFamilyType", "cornerRadius", "bgStrokColor", "switchBgColor", "numberOfCols", "arrowDirection", "carouselCount", "preferredMaxLayoutWidth", "topInset", "highlightTextColor", "leftInset", "radius", "directionType", "numberOfRows", "startColor", "borderWidth", "color", "strokeColor", "filterGift", "lineWidth", "image", "borderWidthValue", "layer.masksToBounds", "textColor", "layer.borderWidth", "autoDismiss", "wp_insetsLeft", "placeholderLabel.textColor", "runningStrokColor", "showCornerAnyTime", "borderColor", "bgLineWidth", "teamNumber", "height", "isScrollable", "needHiddenHighlightBg", "fillColor", "hideWhenZero", "defaultSelectIndex", "runningLineWidth", "fontSize_", "editable", "onlyShowWhitColor", "isDecreaseClockwise", "text", "style", 	],
            "value":		["我真羡慕你，有我这样的朋友！", "给你的汤取个名字吧，10字以内哦~", "1", "sayguess_camera_on", "20", "这里写下汤面的精彩内容吧，200字以内哦~", "4", "这里写下汤底的精彩内容吧，600字以内哦~", "sayguess_call_icon", "NO", "女士是杂技团的一名演员，那天她去买了一双红色的高跟鞋。结果因为她的高跟鞋，她比平时高出了几公分，没有调整过来", "normal_box_bubble", "sayguess_question_mark_icon", "2", "最多150字", "YES", "13.5", "11", "请写下你要发布的线索，30字以内哦～", "sayguess_camera_off", "8", "5hhhttwt", "请输入10-180字符", "22", "6", 	],
        ],
    "progressView":
        [	"opaque":		["NO"],
            "placeholderIntrinsicWidth":		["329"],
            "id":		["QUF-q5-4aG"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "contentMode":		["scaleToFill"],
            "placeholderIntrinsicHeight":		["4"],
            "verticalHuggingPriority":		["750"],
        ],
    "integer":
        [	"key":		["value", "NSUnderline", 	],
            "value":		["16"],
        ],
    "segments":
        [:	],
    "options":
        [:	],
    "rect":
        [	"height":		["152"],
            "y":		["74"],
            "key":		["contentStretch", "frame"],
            "width":		["281"],
            "x":		["86.5"],
        ],
    "mask":
        [	"key":		["constraints"],
        ],
    "offsetWrapper":
        [	"horizontal":		["0.0"],
            "key":		["searchTextPositionAdjustment"],
            "vertical":		["0.0"],
        ],
    "imageReference":
        [	"image":		["chambler_kill_create_standard"],
            "key":		["image", "backgroundImage"],
        ],
    "activityIndicatorView":
        [	"hidesWhenStopped":		["YES", 	],
            "hidden":		["YES", 	],
            "opaque":		["NO", 	],
            "style":		["gray", 	],
            "horizontalHuggingPriority":		["750", 	],
            "id":		["p6U-od-jEt"],
            "contentMode":		["scaleToFill"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "verticalHuggingPriority":		["750"],
            "tag":		["105"],
            "userLabel":		["Sending"],
        ],
    "switch":
        [	"on":		["YES"],
            "contentHorizontalAlignment":		["center"],
            "contentVerticalAlignment":		["center"],
            "tag":		["5", 	],
            "fixedFrame":		["YES", 	],
            "verticalHuggingPriority":		["750", 	],
            "translatesAutoresizingMaskIntoConstraints":		["NO", 	],
            "id":		["OAe-qc-zrq"],
            "horizontalHuggingPriority":		["750"],
            "contentMode":		["scaleToFill"],
            "opaque":		["NO", 	],
        ],
    "constraint":
        [	"firstAttribute":		["height", "bottomMargin", "centerY", "firstBaseline", "top", "right", "trailingMargin", "bottom", "width", "leading", "centerX", "trailing", "leadingMargin", "baseline", 	],
            "userLabel":		["SendFlowerBtn.trailing = Send666Btn.leading", 	],
            "constant":		["228"],
            "relation":		["greaterThanOrEqual", "lessThanOrEqual", 	],
            "id":		["oPW-VY-6XG"],
            "priority":		["200"],
            "symbolic":		["YES", 	],
            "identifier":		["I", 	],
            "secondAttribute":		["firstBaseline", "leadingMargin", "height", "width", "topMargin", "top", "bottomMargin", "trailingMargin", "centerXWithinMargins", "centerYWithinMargins", "bottom", "baseline", "right", "trailing", "centerY", "centerX", "leading", 	],
            "multiplier":		["29:47", "1.00625"],
            "secondItem":		["EfP-iz-qq4"],
            "firstItem":		["Kec-Ro-Q69"],
        ],
    "searchBar":
        [	"id":		["Fye-dn-pTB", "wHg-O4-T4x", "5ja-s2-S1K", 	],
            "showsCancelButton":		["YES", 	],
            "placeholder":		["搜索昵称、备注", 	],
            "contentMode":		["redraw", "scaleAspectFill", 	],
            "translatesAutoresizingMaskIntoConstraints":		["NO", 	],
            "backgroundImage":		["home_empty", 	],
            "searchBarStyle":		["minimal", 	],
        ],
    "mutableString":
        [	"key":		["text", 	],
        ],
    "adaptation":
        [	"id":		["fullscreen", 	],
        ],
    "color":
        [	"colorSpace":		["calibratedWhite", "custom", "calibratedRGB", "catalog", 	],
            "customColorSpace":		["calibratedWhite", "genericGamma22GrayColorSpace", "calibratedRGB", "sRGB", 	],
            "blue":		["0.90980392156862744"],
            "alpha":		["0.080000000000000002"],
            "systemColor":		["systemRedColor", "systemMintColor", "scrollViewTexturedBackgroundColor", "systemBackgroundColor", "labelColor", "darkTextColor", "linkColor", "systemBlueColor", "groupTableViewBackgroundColor", 	],
            "red":		["0.91764705882352937"],
            "green":		["0.16078431372549018"],
            "key":		["value", "pageIndicatorTintColor", "titleShadowColor", "titleColor", "NSBackgroundColor", "baseForegroundColor", "maximumTrackTintColor", "barTintColor", "sectionIndexBackgroundColor", "separatorColor", "NSColor", "progressTintColor", "currentPageIndicatorTintColor", "NSStrokeColor", "selectedSegmentTintColor", "NSUnderlineColor", "textColor", "tintColor", "highlightedColor", "backgroundColor", "trackTintColor", "minimumTrackTintColor", "onTintColor", 	],
            "white":		["0.66666666666666663"],
            "cocoaTouchSystemColor":		["darkTextColor", "whiteColor", "tableCellGroupedBackgroundColor", "groupTableViewBackgroundColor", 	],
            "catalog":		["System", 	],
            "name":		["textColor", 	],
        ],
    "fontDescription":
        [	"pointSize":		["15.600000381469727"],
            "type":		["boldSystem", "system", 	],
            "name":		["PingFangSC-Medium", "PingFangSC-Regular", "BananaPie-Heavy", "PingFangSC-Semibold", "BananaPie-Regular", "DINAlternate-Bold", "HelveticaNeue-Medium", "Helvetica-Bold", "HelveticaNeue", ".AppleSystemUIFont", ".PingFangSC-Regular", "ArialRoundedMTBold", "BananaPie-Semibold", 	],
            "family":		[".AppleSystemUIFont", "PingFang SC", "DIN Alternate", "Helvetica", ".PingFang SC", "Arial Rounded MT Bold", "Helvetica Neue", "Banana Pie", ".AppleSimplifiedChineseFont", 	],
            "weight":		["semibold", "medium", "heavy", 	],
            "key":		["fontDescription", 	],
        ],
    "state":
        [	"backgroundImage":		["green_button"],
            "key":		["selected", "highlighted", "disabled", "normal", 	],
            "image":		["cp_more"],
            "title":		["收起"],
        ],
    "simulatedStatusBarMetrics":
        [	"key":		["statusBar", 	],
        ],
    "stackView":
        [	"insetsLayoutMarginsFromSafeArea":		["NO"],
            "customClass":		["HWHitTestStackView"],
            "contentMode":		["scaleToFill"],
            "alignment":		["top", "center", "bottom"],
            "id":		["bhU-of-UrR"],
            "customModuleProvider":		["target"],
            "ambiguous":		["YES"],
            "userLabel":		["Clue Stack View"],
            "tag":		["9999"],
            "placeholderIntrinsicWidth":		["417"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "distribution":		["equalSpacing", "fillProportionally", "fillEqually", 	],
            "hidden":		["YES"],
            "misplaced":		["YES"],
            "opaque":		["NO"],
            "placeholderIntrinsicHeight":		["120"],
            "horizontalCompressionResistancePriority":		["1000"],
            "horizontalHuggingPriority":		["260"],
            "axis":		["vertical"],
            "semanticContentAttribute":		["forceRightToLeft"],
            "spacing":		["22"],
        ],
    "dependencies":
        [:	],
    "freeformSimulatedSizeMetrics":
        [	"key":		["simulatedDestinationMetrics"],
        ],
    "pageControl":
        [	"translatesAutoresizingMaskIntoConstraints":		["NO"],
            "contentHorizontalAlignment":		["center"],
            "id":		["5Ta-LB-gmS"],
            "opaque":		["NO"],
            "contentMode":		["scaleToFill"],
            "enabled":		["NO"],
            "contentVerticalAlignment":		["bottom", "center"],
            "hidesForSinglePage":		["YES"],
            "numberOfPages":		["3"],
        ],
    "view":
        [	"userLabel":		["changePassword"],
            "contentMode":		["scaleAspectFill", "scaleToFill", "center", "scaleAspectFit"],
            "horizontalHuggingPriority":		["252", "251", "248"],
            "tag":		["107"],
            "id":		["SKL-Pv-jh8"],
            "horizontalCompressionResistancePriority":		["747"],
            "customClass":		["HWChatJsShareContentView"],
            "clearsContextBeforeDrawing":		["NO"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "verticalHuggingPriority":		["400"],
            "verticalCompressionResistancePriority":		["751"],
            "fixedFrame":		["YES"],
            "clipsSubviews":		["YES"],
            "key":		["contentView", "tableFooterView", "tableHeaderView"],
            "ambiguous":		["YES"],
            "verifyAmbiguity":		["ignoreSizes"],
            "multipleTouchEnabled":		["YES"],
            "placeholderIntrinsicWidth":		["342.5", "300", "infinite"],
            "placeholderIntrinsicHeight":		["513.5"],
            "opaque":		["NO"],
            "userInteractionEnabled":		["NO"],
            "autoresizesSubviews":		["NO"],
            "misplaced":		["YES"],
            "insetsLayoutMarginsFromSafeArea":		["NO"],
            "hidden":		["YES"],
            "alpha":		["0.90000000000000002"],
        ],
    "simulatedScreenMetrics":
        [	"type":		["retina4", "retina47"],
            "key":		["simulatedDestinationMetrics", "destination"],
        ],
    "size":
        [	"height":		["36", "0.0"],
            "key":		["headerReferenceSize", "itemSize", "shadowOffset", "footerReferenceSize", "customSize", "intrinsicContentSize", 	],
            "width":		["36", "0.0"],
        ],
    "mutableData":
        [	"key":		["keyedArchiveRepresentation"],
        ],
    "placeholder":
        [	"placeholderIdentifier":		["IBFirstResponder", "IBFilesOwner"],
            "customClass":		["WPSayGuessGameSeatView"],
            "userLabel":		["File's Owner"],
            "id":		["-2", "-1"],
        ],
    "constraints":
        [:	],
    "customFonts":
        [	"key":		["customFonts"],
        ],
    "nil":
        [	"key":		["textColor", "highlightedColor", "simulatedTopBarMetrics", "simulatedStatusBarMetrics", "simulatedBottomBarMetrics"],
        ],
    "textField":
        [	"tag":		["1", "4", "5", "2", "3"],
            "background":		["wedding_textfiled_bg"],
            "userLabel":		["Trail Lyric One"],
            "verticalHuggingPriority":		["251"],
            "clearButtonMode":		["whileEditing", "always"],
            "text":		["..."],
            "contentHorizontalAlignment":		["left"],
            "contentVerticalAlignment":		["center"],
            "clipsSubviews":		["YES"],
            "placeholder":		["不可超过本家族人数"],
            "customClass":		["HWCustomTextField"],
            "borderStyle":		["roundedRect"],
            "textAlignment":		["natural", "center", "right"],
            "verticalCompressionResistancePriority":		["749"],
            "horizontalCompressionResistancePriority":		["748"],
            "contentMode":		["scaleToFill"],
            "horizontalHuggingPriority":		["251"],
            "opaque":		["NO"],
            "minimumFontSize":		["17"],
            "clearsOnBeginEditing":		["YES"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
            "id":		["Adl-a7-KCe"],
        ],
    "image":
        [	"height":		["17"],
            "width":		["76"],
            "name":		["marry_ringBox_bg"],
        ],
    "pickerView":
        [	"userLabel":		["LocatePicker"],
            "contentMode":		["scaleToFill"],
            "id":		["5TG-lS-Z9T", "3"],
            "translatesAutoresizingMaskIntoConstraints":		["NO"],
        ],
    "locale":
        [	"key":		["locale"],
            "localeIdentifier":		["zh_CN"],
        ],
    "systemColor":
        [	"name":		["scrollViewTexturedBackgroundColor", "systemMintColor", "systemBlueColor", "darkTextColor", "groupTableViewBackgroundColor", "labelColor", "systemBackgroundColor", "systemRedColor"],
        ],
]
